### ISSUE TITLE
Compatibility with Clojure 1.2

### ISSUE THREAD

**Issue by hellonico** [Flamefork/fleet#3]
To get fleet to run with Clojure 1.2, I had to copy over the escape-xml code that disappeared in the new clojure*.jar.

== escapeme.clj === (the namespace has to be included in a few different places for the tests to pass)

(ns escapeme)

(def ^{:private true}
     escape-xml-map
     (zipmap "'<>\"&" (map #(str & % \;) '[apos lt gt quot amp])))

(defn escape-xml [text](apply str %28map #%28escape-xml-map % %%29 text%29))
== ===

Awesome template framework by the way ;)

**Comment by Flamefork** [comment]
Just pushed to clojars a new version 0.9.3 which is compatible with clojure & contrib 1.2
Thanks!

**Comment by hellonico** [comment]
0.9.3 works like a charm.

Thank you Starfleet commander ;)
